### ISSUE TITLE
Debug print in form clean() method

### ISSUE THREAD

**Issue by washeck** [carltongibson/django-unique-user-email#11]
It feels to me like a forgotten debug print, otherwise I find it difficult to understand why there should be a print in `clean`.

https://github.com/carltongibson/django-unique-user-email/blob/a383fa85ed7fa3002202e26c6027b7fb4b665b5f/src/unique_user_email/forms.py#L55

**Comment by carltongibson** [comment]
@washeck Fancy removing that?
