### ISSUE TITLE
Compatibility with custom User model

### ISSUE THREAD

**Issue by H4rryK4ne** [carltongibson/django-unique-user-email#9]
Hi Carlton, 

In my project I followed the django documentation suggestion to create a custom User model (although nothing actually happens there). To make your app run with a custom User model I needed to change it a bit.

Instead of importing  `from django.contrib.auth.models import User` I used `User = get_user_model()` .

I can create a PR If you like this.

**Comment by carltongibson** [comment]
Hi @H4rryK4ne — this project doesn't make any sense if you use a custom user model. 

If you do that, just make the `email` field unique. You might even make it your [USERNAME_FIELD](https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD)
